package io.github.qaiserarbi.retellai.model.chat;

import java.util.List;

/**
 * Response of a chat completion: the new messages generated by the agent during
 * this completion, including any tool call invocations and their results. Does
 * not include the original input messages.
 *
 * @param messages the newly generated messages.
 */
public record CreateChatCompletionResponse(
        List<MessageOrToolCall> messages) {
}
