package io.github.qaiserarbi.retellai.model.test;

import io.github.qaiserarbi.retellai.model.chat.MessageOrToolCall;
import java.util.List;
import java.util.Map;

/**
 * Response for a stateless agent playground completion. Contains only the newly
 * generated messages; does not include the input messages.
 *
 * @param messages                       new messages generated by the agent
 * @param currentState                   current state name (retell-llm agents)
 * @param currentNodeId                  current node id (conversation-flow agents)
 * @param dynamicVariables               updated dynamic variables after this turn
 * @param callEnded                      whether the agent ended the conversation
 * @param knowledgeBaseRetrievedContents knowledge base chunks retrieved for this turn
 */
public record AgentPlaygroundCompletionResponse(
        List<MessageOrToolCall> messages,
        String currentState,
        String currentNodeId,
        Map<String, String> dynamicVariables,
        Boolean callEnded,
        List<String> knowledgeBaseRetrievedContents
) {
}
